#pragma once

//
// Macros
//

#define STARTUP_MESSAGE "Welcome to NanoMod! Have a very safe day.\n"

#define NANO_GENERIC_XPBONUS 10
#define NANO_PENALTY_XPBONUS -20
#define NANO_SECRET_XPBONUS 1000000
#define NANO_SCOREREPORT_INTERVAL 100
#define KILL_REWARD_MULTIPLIER 0.5
#define SKILLCOST_INTERMEDIATE 100
#define SKILLCOST_ADVANCED 200
#define DEFAULT_SKILL_POINTS 1069
#define NANO_BLEED_DAMAGE 50
#define NANO_THINKDELAY 1
#define NANO_EXPLOSION_UPSCALE 1.75
#define NANO_CHEAT 69


//
// Agility stats
//

#define NORMAL_SPEED 1.0f
#define BEGINNER_WALK_SPEED NORMAL_SPEED
#define INTERMEDIATE_WALK_SPEED 1.125f
#define ADVANCED_WALK_SPEED 1.25f

#define BEGINNER_RUN_SPEED 1.3f
#define INTERMEDIATE_RUN_SPEED 1.5f
#define ADVANCED_RUN_SPEED 1.7f

#define DEFAULT_JUMP 1.0f

#define BEGINNER_JUMP_BEAST 1.25
#define INTERMEDIATE_JUMP_BEAST 1.6f
#define ADVANCED_JUMP_BEAST 2.0f

#define BEGINNER_JUMP_NORMAL DEFAULT_JUMP
#define INTERMEDIATE_JUMP_NORMAL 1.25f
#define ADVANCED_JUMP_NORMAL 1.5f

// Make longjump an enviro skill? Maybe make hazard skill a "suit upgrade"
#define LONGJUMP_SPEED_BEGINNER 560
#define LONGJUMP_SPEED_INTERMEDIATE 680
#define LONGJUMP_SPEED_ADVANCED 800

//
// Swimming stats
//

#define BEGINNER_SWIM_SPEED 0.8
#define INTERMEDIATE_SWIM_SPEED 1.1
#define ADVANCED_SWIM_SPEED 1.3

#define BEGINNER_DROWN_DMG 5
#define INTERMEDIATE_DROWN_DMG 3
#define ADVANCED_DROWN_DMG 1

#define AIRGASP_BEGINNER 10
#define AIRGASP_INTERMEDIATE 25
#define AIRGASP_ADVANCED 50


//
// Misc (to sort)
//

#define BANDAGE_TIME_BEGINNER 5
#define BANDAGE_TIME_INTERMEDIATE 3
#define BANDAGE_TIME_ADVANCED 1

#define HEV_MAX_CHARGE_BEGINNER 100
#define HEV_MAX_CHARGE_INTERMEDIATE 150
#define HEV_MAX_CHARGE_ADVANCED 200
#define BATTERY_CELL_CHARGE 35

#define FOOTSTEP_VOLUME_LOW 0.15
#define FOOTSTEP_VOLUME_MEDIUM 0.3
#define FOOTSTEP_VOLUME_HIGH 0.5

#define DAMAGE_REDUCTION_BEGINNER 1.0
#define DAMAGE_REDUCTION_INTERMEDIATE 0.75
#define DAMAGE_REDUCTION_ADVANCED 0.5

#define HITPUNCH_BEGINNER -2
#define HITPUNCH_INTERMEDIATE -1.25
#define HITPUNCH_ADVANCED -0.5

#define FALLDAMAGE_INTERMEDIATE 0.4
#define FALLDAMAGE_ADVANCED 0.25

//#define HUMAN_GRUNT_HEALTH 125


//
// Weapon mechanics
//

#define CROWBAR_FIRST_SWING_DELAY 0.5
#define CROWBAR_DEFAULT_DAMAGE gSkillData.plrDmgCrowbar
#define CROWBAR_DEFAULT_RESWING_DELAY 0.25
#define CROWBAR_HEAVY_RESWING_DELAY 0.5
#define CROWBAR_NORMAL_RESWING_DELAY 0.37
#define CROWBAR_SUPERSWING_DMG 69

#define NANO_CROWBAR_NERF 0.7
#define NANO_MELEE_SWINGDELAY 3

#define DEAGLE_DAMAGE 999
#define DEAGLE_LASERSPOT_ACCURACY VECTOR_CONE_4DEGREES
#define DEAGLE_NORMAL_ACCURACY VECTOR_CONE_11DEGREES
#define LASER_SPOT_SCALE 0.25

#define GAUSS_REFIRE_BEGINNER 0.8
#define GAUSS_REFIRE_INTERMEDIATE 0.42
#define GAUSS_REFIRE_ADVANCED 0.2

#define SATCHEL_VELOCITY_BEGINNER 274
#define SATCHEL_VELOCITY_INTERMEDIATE 650
#define SATCHEL_VELOCITY_ADVANCED 1000

#define GRENADE_VELOCITY_BEGINNER 6.5f
#define GRENADE_VELOCITY_INTERMEDIATE 13.0f
#define GRENADE_VELOCITY_ADVANCED 10.0f

#define SHOTGUN_DISTANCE_BEGINNER 2048
#define SHOTGUN_DISTANCE_INTERMEDIATE 4096
#define SHOTGUN_DISTANCE_ADVANCED 8192

#define EXPLOSIONSCALE_BEGINNER 1.6
#define EXPLOSIONSCALE_INTERMEDIATE 1.3
#define EXPLOSIONSCALE_ADVANCED 1.0

// TODO:
// melee superswing 3 levels
// 


//
// Enums
//

enum SkillLevel
{
	SKILL_BEGINNER,
	SKILL_INTERMEDIATE,
	SKILL_ADVANCED,
	MAX_SKILLLEVELS,
};

/*enum SkillTypes
{
	SKILL_WEAPONS_MELEE,
	SKILL_WEAPONS_BULLET,
	SKILL_WEAPONS_EXPLOSIVE,
	SKILL_WEAPONS_ENERGY,
	SKILL_WEAPONS_ALIEN,
	SKILL_AGILITY,
	SKILL_HAZARD,
	SKILL_STEALTH,
	SKILL_SWIMMING,
	SKILL_SLOWMO,
	SKILL_TYPE_MAX,
};*/

enum NewSkillTypes
{
	SKILL_HEAD,
	SKILL_TORSO,
	SKILL_ARMS,
	SKILL_LEGS,
	SKILL_FIRMWARE,
	SKILL_WEAPONS_BULLET,
	SKILL_WEAPONS_SPECIAL,
	SKILL_STEALTH,
	SKILL_HAZARD,
	SKILL_TIME,
	SKILL_TYPE_MAX,
};

enum PlayerItems
{
	ITEM_MEDKIT,
	ITEM_BATTERY,
	ITEM_ANTIDOTE,
	ITEM_ADRENALINE,
	ITEM_RADIATION,
	ITEM_AIRTANK,
	ITEM_SECURITY,
};

enum AccuracyTypes
{
	ACCURACY_POOR,
	ACCURACY_NORMAL,
	ACCURACY_BETTER,
	ACCURACY_EXCELLENT,
	ACCURACY_ULTRA,
	ACCURACY_MAX,
};

enum BulletWeaponTypes
{
	BULLETWEAPON_MACHINEGUNS,
	BULLETWEAPON_SHOTGUN,
	BULLETWEAPON_LIGHTPISTOL,
	BULLETWEAPON_HEAVYPISTOL,
	BULLETWEAPON_MAX,
};

enum AmmoTypes
{
	AMMO_9MM,
	AMMO_BUCKSHOT,
	AMMO_BOLTS,
	AMMO_357,
	AMMO_ROCKET,
	AMMO_URANIUM,
	AMMO_GRENADE,
	AMMO_SATCHEL,
	AMMO_TRIPMINE,
	AMMO_SNARK,
	AMMO_HORNETS,
};

enum WeaponTypes
{
	BULLET_WEAPONS,
	EXPLOSIVE_WEAPONS,
	ENERGY_WEAPONS,
	ALIEN_WEAPONS,
};

enum SkillPoints
{
	SKILL_POINTS_WEAPON,
	SKILL_POINTS_GENERAL,
	SKILL_POINTS_MAX,
};

enum CrowbarSwings
{
	NORMAL_SWING,
	HEAVY_SWING,
};

enum WeaponMenuColumn
{
	COLUMN_1,
	COLUMN_2,
	COLUMN_3,
	COLUMN_4,
	COLUMN_5,
	COLUMN_6,
	COLUMN_7,
	MAX_COLUMNS,
};

enum WeaponMenuRow
{
	ROW_1,
	ROW_2,
	ROW_3,
	ROW_4,
	MAX_ROWS,
};

enum ShowXPLevel
{
	SHOW_NO_XPMSGS,
	SHOW_LESS_XPMSGS,
	SHOW_ALL_XPMSGS,
};

enum BodyParts
{
	GENERIC_DMG,
	HEAD_DMG,
	TORSO_DMG,
	//CHEST_DMG,
	//STOMACH_DMG,
	ARMS_DMG,
	LEGS_DMG,
	//LEFTARM_DMG,
	//RIGHTARM_DMG,
	//LEFTLEG_DMG,
	//RIGHTLEG_DMG,
	MAX_BODYPARTS
};

struct DefaultWeaponMenu
{
	int Column[MAX_WEAPONS];
	int Row[MAX_WEAPONS];
};

struct AlternateWeaponMenu
{
	int Column[MAX_WEAPONS];
	int Row[MAX_WEAPONS];
};


//
// Accuracy
//

#define ACCURACY_FIRING_DELAY 0.8

#define ACCURACY_PENALTY_BEGINNER 2.0
#define ACCURACY_PENALTY_INTERMEDIATE 1.5
#define ACCURACY_PENALTY_NONE 1.0

#define DEFAULT_ACCURACY_BEGINNER VECTOR_CONE_15DEGREES
#define DEFAULT_ACCURACY_INTERMEDIATE VECTOR_CONE_8DEGREES
#define DEFAULT_ACCURACY_ADVANCED VECTOR_CONE_1DEGREES
#define NOT_USED Vector(0.0, 0.0, 0.0);

#define ACCURACY_MACHINEGUN_BEGINNER_POOR VECTOR_CONE_12DEGREES;
#define ACCURACY_MACHINEGUN_BEGINNER_NORMAL VECTOR_CONE_6DEGREES;
#define ACCURACY_MACHINEGUN_BEGINNER_BETTER VECTOR_CONE_5DEGREES;
#define ACCURACY_MACHINEGUN_BEGINNER_EXCELLENT VECTOR_CONE_4DEGREES;
#define ACCURACY_MACHINEGUN_BEGINNER_ULTRA VECTOR_CONE_2DEGREES;

#define ACCURACY_MACHINEGUN_INTERMEDIATE_POOR VECTOR_CONE_8DEGREES;
#define ACCURACY_MACHINEGUN_INTERMEDIATE_NORMAL VECTOR_CONE_6DEGREES;
#define ACCURACY_MACHINEGUN_INTERMEDIATE_BETTER VECTOR_CONE_4DEGREES;
#define ACCURACY_MACHINEGUN_INTERMEDIATE_EXCELLENT VECTOR_CONE_3DEGREES;
#define ACCURACY_MACHINEGUN_INTERMEDIATE_ULTRA VECTOR_CONE_2DEGREES;

#define ACCURACY_MACHINEGUN_ADVANCED_POOR VECTOR_CONE_4DEGREES;
#define ACCURACY_MACHINEGUN_ADVANCED_NORMAL VECTOR_CONE_3DEGREES;
#define ACCURACY_MACHINEGUN_ADVANCED_BETTER VECTOR_CONE_3DEGREES;
#define ACCURACY_MACHINEGUN_ADVANCED_EXCELLENT VECTOR_CONE_2DEGREES;
#define ACCURACY_MACHINEGUN_ADVANCED_ULTRA VECTOR_CONE_1DEGREES;

#define ACCURACY_SHOTGUN_BEGINNER_POOR VECTOR_CONE_15DEGREES
#define ACCURACY_SHOTGUN_BEGINNER_NORMAL VECTOR_CONE_12DEGREES
#define ACCURACY_SHOTGUN_BEGINNER_BETTER VECTOR_CONE_9DEGREES

#define ACCURACY_SHOTGUN_INTERMEDIATE_POOR VECTOR_CONE_15DEGREES
#define ACCURACY_SHOTGUN_INTERMEDIATE_NORMAL VECTOR_CONE_10DEGREES
#define ACCURACY_SHOTGUN_INTERMEDIATE_BETTER VECTOR_CONE_8DEGREES

#define ACCURACY_SHOTGUN_ADVANCED_POOR VECTOR_CONE_10DEGREES
#define ACCURACY_SHOTGUN_ADVANCED_NORMAL VECTOR_CONE_5DEGREES
#define ACCURACY_SHOTGUN_ADVANCED_BETTER VECTOR_CONE_1DEGREES

#define ACCURACY_LIGHTPISTOL_BEGINNER_POOR VECTOR_CONE_12DEGREES
#define ACCURACY_LIGHTPISTOL_BEGINNER_NORMAL VECTOR_CONE_5DEGREES
#define ACCURACY_LIGHTPISTOL_BEGINNER_BETTER VECTOR_CONE_4DEGREES

#define ACCURACY_LIGHTPISTOL_INTERMEDIATE_POOR VECTOR_CONE_10DEGREES
#define ACCURACY_LIGHTPISTOL_INTERMEDIATE_NORMAL VECTOR_CONE_6DEGREES
#define ACCURACY_LIGHTPISTOL_INTERMEDIATE_BETTER VECTOR_CONE_3DEGREES

#define ACCURACY_LIGHTPISTOL_ADVANCED_POOR VECTOR_CONE_5DEGREES
#define ACCURACY_LIGHTPISTOL_ADVANCED_NORMAL VECTOR_CONE_2DEGREES
#define ACCURACY_LIGHTPISTOL_ADVANCED_BETTER VECTOR_CONE_1DEGREES

#define ACCURACY_HEAVYPISTOL_BEGINNER_POOR VECTOR_CONE_17DEGREES
#define ACCURACY_HEAVYPISTOL_BEGINNER_NORMAL VECTOR_CONE_7DEGREES
#define ACCURACY_HEAVYPISTOL_BEGINNER_BETTER VECTOR_CONE_4DEGREES
#define ACCURACY_HEAVYPISTOL_BEGINNER_EXCELLENT VECTOR_CONE_2DEGREES
#define ACCURACY_HEAVYPISTOL_BEGINNER_ULTRA VECTOR_CONE_1DEGREES

#define ACCURACY_HEAVYPISTOL_INTERMEDIATE_POOR VECTOR_CONE_17DEGREES
#define ACCURACY_HEAVYPISTOL_INTERMEDIATE_NORMAL VECTOR_CONE_7DEGREES
#define ACCURACY_HEAVYPISTOL_INTERMEDIATE_BETTER VECTOR_CONE_4DEGREES
#define ACCURACY_HEAVYPISTOL_INTERMEDIATE_EXCELLENT VECTOR_CONE_2DEGREES
#define ACCURACY_HEAVYPISTOL_INTERMEDIATE_ULTRA VECTOR_CONE_1DEGREES

#define ACCURACY_HEAVYPISTOL_ADVANCED_POOR VECTOR_CONE_17DEGREES
#define ACCURACY_HEAVYPISTOL_ADVANCED_NORMAL VECTOR_CONE_7DEGREES
#define ACCURACY_HEAVYPISTOL_ADVANCED_BETTER VECTOR_CONE_4DEGREES
#define ACCURACY_HEAVYPISTOL_ADVANCED_EXCELLENT VECTOR_CONE_2DEGREES
#define ACCURACY_HEAVYPISTOL_ADVANCED_ULTRA VECTOR_CONE_1DEGREES


//
// Recoil
//

#define NO_RECOIL 0.0f
#define JUMPING_RECOIL 3.0f

#define AK47_RECOIL_BEGINNER 2.5f
#define AK47_RECOIL_INTERMEDIATE 1.75f
#define AK47_RECOIL_ADVANCED 1.0f

#define GENERIC_RECOIL_BEGINNER 1.25f
#define GENERIC_RECOIL_INTERMEDIATE 0.75f
#define GENERIC_RECOIL_ADVANCED .33f

#define GLOCK_RECOIL_BEGINNER 1.25
#define GLOCK_RECOIL_INTERMEDIATE 0.75
#define GLOCK_RECOIL_ADVANCED 0.25

#define GAUSS_RECOIL_BEGINNER 10.0
#define GAUSS_RECOIL_INTERMEDIATE 5.0
#define GAUSS_RECOIL_ADVANCED 0.0

#define EGON_RECOIL_BEGINNER 0.2f
#define EGON_RECOIL_INTERMEDIATE 0.15f
#define EGON_RECOIL_ADVANCED 0.1f


//
// Max ammo carry
//

#define URANIUM_MAX_CARRY_INCREASED 200
#define _9MM_MAX_CARRY_INCREASED 300
#define _357_MAX_CARRY_INCREASED 48
#define BUCKSHOT_MAX_CARRY_INCREASED 150
#define BOLT_MAX_CARRY_INCREASED 70
#define ROCKET_MAX_CARRY_INCREASED 8
#define HANDGRENADE_MAX_CARRY_INCREASED 12
#define SATCHEL_MAX_CARRY_INCREASED 8
#define TRIPMINE_MAX_CARRY_INCREASED 8
#define SNARK_MAX_CARRY_INCREASED 20
#define HORNET_MAX_CARRY_INCREASED 12
#define M203_GRENADE_MAX_CARRY_INCREASED 12

#define URANIUM_MAX_CARRY_MAXED 300
#define _9MM_MAX_CARRY_MAXED 350
#define _357_MAX_CARRY_MAXED 72
#define BUCKSHOT_MAX_CARRY_MAXED 200
#define BOLT_MAX_CARRY_MAXED 100
#define ROCKET_MAX_CARRY_MAXED 15
#define HANDGRENADE_MAX_CARRY_MAXED 15
#define SATCHEL_MAX_CARRY_MAXED 12
#define TRIPMINE_MAX_CARRY_MAXED 12
#define SNARK_MAX_CARRY_MAXED 30
#define HORNET_MAX_CARRY_MAXED 16
#define M203_GRENADE_MAX_CARRY_MAXED 15